### ISSUE TITLE
Way to send funds to created contracts (manually enter swap address)

### ISSUE THREAD

**Issue by themandalore** [DecentralizedDerivatives/DRCT_standard_DApp#142]
If the party does the first part of 'create contract' they will have a swap address.  I want to have a way to still send funds if you click away during the creation process.  This should be a link at the bottom of the 'Create Contract' modal that says 'Already Have a created contract?' and then it gives you a field to paste in an address and will let you send funds to it

**Comment by gainsboroughtech** [comment]
Done
