### ISSUE TITLE
Check if approved when list

### ISSUE THREAD

**Issue by themandalore** [DecentralizedDerivatives/DRCT_standard_DApp#176]
The dapp should check if they are already approved (total approved = total listed)...still thinking of the best way to do this

**Comment by themandalore** [comment]
//The first piece to check if approved, when sending the 'Approve' order, 
//check total amount approved for this token being listed:
drct.allowance(user_address,exchange.address);
//If the amount being listed is less than the amount already approved:
//check total listed of the asset:  
exchange.getUserOrders(user_address)
//this will return an array of orderId's
//Loop through these OrderId's:
exchange.getOrder(order_id);
//this will return 4 values, the maker, price, amount, asset.
//create a sum of all amounts if the asset is the token being listed now,
//If the total amount approved is greater than the total amount listed + new amount your listing, 
//then just return a 'Approved to List' message and skip the approval metamask call.

**Comment by gainsboroughtech** [comment]
Done
