### ISSUE TITLE
Add real time amount gained

### ISSUE THREAD

**Issue by themandalore** [DecentralizedDerivatives/DRCT_standard_DApp#248]
This is for the My Portfolio page and the Bulletin

**Comment by themandalore** [comment]
Next to token, add in a number (red if negative, green if positive) of % gained. 
To get this, you would take the start price (call the oracle on the start date) and then do an api call to GDAX (look at the graph for examples of this).  Use the most recent price and calculate percentage change.

If the contract has not started yet, just put (--) in dark grey

**Comment by gainsboroughtech** [comment]
Done
