### ISSUE TITLE
Issue getting user orders

### ISSUE THREAD

**Issue by taihelsel** [DecentralizedDerivatives/DRCT_standard_DApp#37]
Problem:
Getting the error message below in dev the console when trying to get the user's orders.
```
Error getting orders Error: Invalid number of arguments to Solidity function
```
Culprit:
Line 51 in the Unlist component.
```javascript
const books = await exchange.userOrders.call(this.state.myAccount);
```

**Comment by themandalore** [comment]
Updated the contracts, now its exchange.getUserOrders(this.state.myAccount);
